name: Test Script

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name:  Checkout repo
      uses: actions/checkout@v3

    - name:  Make script executable
      run: chmod +x install.sh

    -- name: Run script
  env:
    DJANGO_SUPERUSER_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
  run: sudo ./install.sh